### PR TITLE
Update Textual >=0.64.0

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Why the aggresive pin, does it now work with older version, and do you expect it to break often?

**Comment by davidbrochart** [comment]
I think Textual is moving so fast that it's best to only support the latest minor version, until it reaches v1.0.
In this case there was a breaking change.

**Comment by maartenbreddels** [comment]
but users can always go back right, I was able to go back to an older textual version, now I'm locked in and don't have solvable environments anymore (except when using uv pip which has an escape hatch for this)

**Comment by maartenbreddels** [comment]
I mean, I understand version pinning for applications, but libraries have to live together in a single environment.

**Comment by davidbrochart** [comment]
I'm not sure I want to support multiple incompatible versions of Textual, and bloat the code with `if/elif` blocks for each version.
In this case I admit it's not a lot though.

**Pull request merged**
